### ISSUE TITLE
Negative numbers in chart data not rendered correctly

### ISSUE THREAD

**Issue by mauthi** [enso-ui/charts#10]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I tried to display negative values in bar chart. The output of values is correct but the bar is not rendered below zero.

![image](https://user-images.githubusercontent.com/7204559/98437617-de0d2300-20e3-11eb-8b8f-09d428d003b2.png)

In the example of chart.js (https://www.chartjs.org/samples/latest/charts/bar/vertical.html) negative values are rendered correctly.

![image](https://user-images.githubusercontent.com/7204559/98437659-4fe56c80-20e4-11eb-8f3e-ab271d5bfd98.png)

### Steps to Reproduce

1. Change a value in ChartController:bar() to a value < 0
2. Open dashboard and look at "Sales" bar chart

### Expected behavior

Negative values should draw a bar below zero

### Actual behavior

Negative values are rendered without bar

**Comment by aocneanu** [comment]
This is intended in our default config.

This package needs a complete rewrite but we keep delaying it because it will have a high complexity and we don't want to break things backward.

Meanwhile you can chain `authYMin()` to your builder and it should solve your problem (after composer update and yarn upgrade)

**Comment by mauthi** [comment]
> Meanwhile you can chain authYMin() to your builder

Small typo in comment: `autoYMin()`

Thx - works.
Info: If you have only negative values axis starts not at 0 - but that's something I can live with.
